DROP TABLE IF EXISTS Address;

CREATE TABLE Address(
AddressId INT AUTO_INCREMENT  PRIMARY KEY,
Street VARCHAR(255) NOT NULL,
Building VARCHAR(255) NOT NULL,
ZipCode VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS RESTAURANT;

CREATE TABLE RESTAURANT(
RestaurantId INT AUTO_INCREMENT  PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
Cuisine VARCHAR(255) NOT NULL,
Borough VARCHAR(255) NOT NULL,
AddressId int NOT NULL
);